# Generated by Django 3.1.7 on 2021-09-11 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('championships', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='stagesLog',
            new_name='stageLogs',
        ),
        migrations.RenameModel(
            old_name='stage',
            new_name='stages',
        ),
    ]
