# Generated by Django 3.1.7 on 2021-09-11 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championships', '0002_auto_20210910_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='championships',
            name='championshipName',
            field=models.CharField(default='Campeonato ..', max_length=200),
        ),
    ]
