# Generated by Django 3.1.7 on 2021-09-11 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championships', '0003_championships_championshipname'),
    ]

    operations = [
        migrations.AddField(
            model_name='stages',
            name='stageName',
            field=models.CharField(default='Etapa ..', max_length=200),
        ),
    ]
