# Generated by Django 3.1.7 on 2021-09-11 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('championships', '0004_stages_stagename'),
    ]

    operations = [
        migrations.AddField(
            model_name='stages',
            name='champId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='championships.championships'),
            preserve_default=False,
        ),
    ]
