# Generated by Django 3.1.7 on 2021-09-10 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='abstractAssignments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='asbtractParticipations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='asbtractPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='competitions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='jumpAssignments',
            fields=[
                ('abstractassignments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='competitions.abstractassignments')),
            ],
            bases=('competitions.abstractassignments',),
        ),
        migrations.CreateModel(
            name='jumpParticipation',
            fields=[
                ('asbtractparticipations_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='competitions.asbtractparticipations')),
            ],
            bases=('competitions.asbtractparticipations',),
        ),
        migrations.CreateModel(
            name='jumpPoints',
            fields=[
                ('asbtractpoints_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='competitions.asbtractpoints')),
            ],
            bases=('competitions.asbtractpoints',),
        ),
        migrations.CreateModel(
            name='mdAssignments',
            fields=[
                ('abstractassignments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='competitions.abstractassignments')),
            ],
            bases=('competitions.abstractassignments',),
        ),
        migrations.CreateModel(
            name='mdPoints',
            fields=[
                ('asbtractpoints_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='competitions.asbtractpoints')),
            ],
            bases=('competitions.asbtractpoints',),
        ),
        migrations.CreateModel(
            name='speedAssignments',
            fields=[
                ('abstractassignments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='competitions.abstractassignments')),
            ],
            bases=('competitions.abstractassignments',),
        ),
        migrations.CreateModel(
            name='speedPoints',
            fields=[
                ('asbtractpoints_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='competitions.asbtractpoints')),
            ],
            bases=('competitions.asbtractpoints',),
        ),
        migrations.CreateModel(
            name='throw',
            fields=[
                ('asbtractparticipations_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='competitions.asbtractparticipations')),
            ],
            bases=('competitions.asbtractparticipations',),
        ),
        migrations.CreateModel(
            name='throwAssignments',
            fields=[
                ('abstractassignments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='competitions.abstractassignments')),
            ],
            bases=('competitions.abstractassignments',),
        ),
        migrations.CreateModel(
            name='throwPoints',
            fields=[
                ('asbtractpoints_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='competitions.asbtractpoints')),
            ],
            bases=('competitions.asbtractpoints',),
        ),
    ]
