# Generated by Django 3.1.7 on 2021-09-11 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('championships', '0005_stages_champid'),
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitions',
            name='eventId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='competitions.events'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='competitions',
            name='gender',
            field=models.IntegerField(choices=[(0, 'SIN GENERO'), (1, 'VARONES'), (2, 'DAMAS')], default=0),
        ),
        migrations.AddField(
            model_name='competitions',
            name='initDate',
            field=models.CharField(default='08:00', max_length=200),
        ),
        migrations.AddField(
            model_name='competitions',
            name='stageId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='championships.stages'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='eventName',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='eventType',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
