# Generated by Django 3.1.7 on 2021-09-15 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_auto_20210911_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='eventName',
            field=models.CharField(default='EVENTO ..', max_length=200),
        ),
        migrations.AlterField(
            model_name='events',
            name='eventType',
            field=models.IntegerField(choices=[(1, 'VELOCIDAD'), (2, 'MEDIOFONDO'), (3, 'SALTO'), (4, 'GARROCHA'), (5, 'LANZAMIENTO')], default=1),
        ),
    ]
