# Generated by Django 3.1.7 on 2021-09-15 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0003_auto_20210915_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='throwHeats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competitionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.competitions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='speedHeats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competitionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.competitions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='mdHeats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competitionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.competitions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='jumpHeats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competitionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.competitions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
