# Generated by Django 3.1.7 on 2021-09-15 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0002_auto_20210915_1836'),
        ('competitions', '0005_auto_20210915_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractassignments',
            name='PB',
            field=models.CharField(default='NPB', max_length=200),
        ),
        migrations.AddField(
            model_name='abstractassignments',
            name='athleteId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='athletes.athletes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='abstractassignments',
            name='place',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='abstractassignments',
            name='result',
            field=models.CharField(default='NR', max_length=200),
        ),
        migrations.AddField(
            model_name='mdassignments',
            name='heatId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='competitions.mdheats'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='speedassignments',
            name='heatId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='competitions.speedheats'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='speedassignments',
            name='line',
            field=models.IntegerField(default=0),
        ),
    ]
