# Generated by Django 3.1.7 on 2021-09-15 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0007_auto_20210915_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdassignments',
            name='heatId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asign', to='competitions.mdheats'),
        ),
    ]
