# Generated by Django 3.1.7 on 2021-09-17 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0008_auto_20210915_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitions',
            name='round',
            field=models.IntegerField(choices=[(0, 'DF'), (1, 'SERIE'), (2, 'SEMIFINAL'), (3, 'FINAL')], default=0),
        ),
    ]
