# Generated by Django 3.1.7 on 2021-09-28 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0003_auto_20210927_2347'),
        ('competitions', '0009_competitions_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitions',
            name='comb',
            field=models.CharField(default='NO', max_length=200),
        ),
        migrations.AlterField(
            model_name='abstractassignments',
            name='athleteId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatedAthle', to='athletes.athletes'),
        ),
        migrations.AlterField(
            model_name='competitions',
            name='gender',
            field=models.IntegerField(choices=[(0, 'SIN GENERO'), (1, 'DAMAS'), (2, 'VARONES')], default=0),
        ),
        migrations.AlterField(
            model_name='competitions',
            name='round',
            field=models.IntegerField(choices=[(0, 'DF'), (1, 'SERIE'), (2, 'SEMIFINAL'), (3, 'FINAL')], default=1),
        ),
        migrations.AlterField(
            model_name='jumpheats',
            name='competitionId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jumpheats', to='competitions.competitions'),
        ),
        migrations.AlterField(
            model_name='mdheats',
            name='competitionId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mdheats', to='competitions.competitions'),
        ),
        migrations.AlterField(
            model_name='speedheats',
            name='competitionId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speedheats', to='competitions.competitions'),
        ),
        migrations.AlterField(
            model_name='throwheats',
            name='competitionId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='throwheats', to='competitions.competitions'),
        ),
    ]
