# Generated by Django 3.1.7 on 2021-09-30 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0010_auto_20210927_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='speedassignments',
            name='pb',
            field=models.CharField(default='99.99', max_length=6),
        ),
    ]
