# Generated by Django 3.1.7 on 2021-09-30 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0011_speedassignments_pb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speedassignments',
            name='pb',
        ),
    ]
