# Generated by Django 3.1.7 on 2021-09-30 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0012_remove_speedassignments_pb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abstractassignments',
            old_name='PB',
            new_name='personalBest',
        ),
    ]
