# Generated by Django 3.1.7 on 2021-09-30 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0013_auto_20210930_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='jumpassignments',
            name='heatId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='asign', to='competitions.jumpheats'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='throwassignments',
            name='heatId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='asign', to='competitions.throwheats'),
            preserve_default=False,
        ),
    ]
