# Generated by Django 3.1.7 on 2021-09-28 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0002_auto_20210915_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athletes',
            name='gender',
            field=models.IntegerField(choices=[(0, 'SIN GENERO'), (1, 'DAMAS'), (2, 'VARONES')], default=1),
        ),
    ]
